### ISSUE TITLE
Question: Serialise / deserialise state

### ISSUE THREAD

**Issue by subcontact** [davestewart/javascript-state-machine#19]
Hi, 
Sorry for raising an issue - I was't sure where to ask the question...

I'm looking for a simple way (API?) to be able to save/serialise the state externally and then create a new state machine at a later time (possible separate process) using the previously saved state.

It's for use in a stateless context over multiple executions.
Any pointers/suggestions?

Great project by the way!

**Comment by davestewart** [comment]
Hey, 

Thanks for the kind words!

It's been ages since I looked at the code, but could you save the base options as JSON, then set the `initial` state?

- http://statemachine.davestewart.io/html/api/states/initial.html

As for doing something more advanced with serialising and hydrating the state, that might be a good feature request. But as I said, I haven't looked at the code for ages, so can't advise on how much work that would / wouldn't be right now!

**Comment by subcontact** [comment]
Thanks for the quick response!
That's enough for me to go with.
Cheers
